general:
  update-notification: true
  prefix: "&7» &eKudos&7: "
  kudo-award-cooldown: 900
  debug-mode: false
  useSQL: true
kudo-award-notification:
  enabled: true
  notification-mode: "broadcast"
  enable-playsound: true
  playsound-type: "ENTITY_PLAYER_LEVELUP"
kudo-award-limitation:
  enabled: true
  cooldown: 86400
  max-kudos-to-receive: 5
award-item:
  enabled: true
  use-lore: false
  item: COOKIE
  item-name: "&6Hot Baked Cookie"
  item-lore:
    - "&7Ingredients:"
    - "&7- Wheat"
    - "&7- Cocoa Beans"
  amount: 1
milestone:
  enabled: true
  span-between-kudos: 10
  enable-playsound: true
  playsound-type: "ENTITY_FIREWORK_ROCKET_TWINKLE"
  reward:
    enabled: true
    use-lore: false
    item: MILK_BUCKET
    item-name: "&6Cold milk"
    item-lore:
      - "&7Suitable for cookies"
    amount: 1